server.port=8080
spring.application.name=api-gateway

# ms-usuarios + auth
spring.cloud.gateway.routes[0].id=ms-usuarios
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.routes[1].id=ms-auth
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**

# ms-pasajes
spring.cloud.gateway.routes[2].id=ms-pasajes
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pasajes/**

# ms-viajes
spring.cloud.gateway.routes[3].id=ms-viajes
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/viajes/**

# ms-encomiendas
spring.cloud.gateway.routes[4].id=ms-encomiendas
spring.cloud.gateway.routes[4].uri=http://localhost:8084
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/encomiendas/**

# ms-auditoria
spring.cloud.gateway.routes[5].id=ms-auditoria
spring.cloud.gateway.routes[5].uri=http://localhost:8085
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/auditoria/**

# CORS para Angular
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

jwt.secret=trans-sync-jwt-secret-key-2026-synergy6-dev-only-must-be-long-enough

management.endpoints.web.exposure.include=health,gateway
