# Puerto de este microservicio
server.port=8081
spring.application.name=ms-usuarios

# Conexión a tu PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/trans_sync_bd_usuarios
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Magia de Spring Boot: Crea/Actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true