### Crear viaje
POST http://localhost:8083/api/viajes
Content-Type: application/json

{
  "numeroViaje": "JUL-CUS-1024",
  "origen": "Juliaca",
  "destino": "Cusco",
  "fechaSalida": "2026-07-25T14:30:00",
  "precio": 45.00,
  "capacidad": 7
}

### Listar viajes activos
GET http://localhost:8083/api/viajes

### Detalle viaje
GET http://localhost:8083/api/viajes/JUL-CUS-1024

### Cancelar viaje
PATCH http://localhost:8083/api/viajes/JUL-CUS-1024/estado
Content-Type: application/json

{
  "estado": "CANCELADO"
}
